import {
  User, Briefcase, Lightbulb, Folder, Hash, Star, Heart, Home,
  Book, Music, Camera, Palette, Globe, Zap, Target, Trophy,
  Rocket, Flame, Cloud, Sun, Moon, Sparkles, Feather, Compass,
  Map, MapPin, Coffee, Pizza, Utensils, Gift, ShoppingBag, ShoppingCart,
  CreditCard, Wallet, DollarSign, TrendingUp, BarChart, PieChart, Activity, Calendar,
  Clock, Bell, Mail, MessageCircle, Phone, Video, Mic, Headphones,
  Film, Image, Bookmark, Tag, Flag, Award, Medal, Crown,
  Gem, Anchor, Plane, Car, Bike, Ship, Train, Bus,
  Trees, Leaf, Flower, Sprout, Fish, Bird, Cat, Dog,
  Code, Terminal, Cpu, Database, Server, Wifi, Lock,
  Key, Shield, Eye, Search, Filter, Layers, Grid, List,
  PenTool, Brush, Scissors, Ruler, Wrench, Hammer, Puzzle, Gamepad,
  Dumbbell, Mountain, Umbrella, Tent, Backpack, Watch, Glasses,
} from 'lucide-react';

export interface WorkspaceIconOption {
  id: string;
  icon: React.ElementType;
  label: string;
}

export const WORKSPACE_ICONS: WorkspaceIconOption[] = [
  { id: 'user', icon: User, label: 'User' },
  { id: 'briefcase', icon: Briefcase, label: 'Work' },
  { id: 'lightbulb', icon: Lightbulb, label: 'Ideas' },
  { id: 'folder', icon: Folder, label: 'Folder' },
  { id: 'hash', icon: Hash, label: 'Tag' },
  { id: 'star', icon: Star, label: 'Star' },
  { id: 'heart', icon: Heart, label: 'Heart' },
  { id: 'home', icon: Home, label: 'Home' },
  { id: 'book', icon: Book, label: 'Book' },
  { id: 'music', icon: Music, label: 'Music' },
  { id: 'camera', icon: Camera, label: 'Camera' },
  { id: 'palette', icon: Palette, label: 'Art' },
  { id: 'globe', icon: Globe, label: 'Travel' },
  { id: 'zap', icon: Zap, label: 'Energy' },
  { id: 'target', icon: Target, label: 'Goals' },
  { id: 'trophy', icon: Trophy, label: 'Wins' },
  { id: 'rocket', icon: Rocket, label: 'Launch' },
  { id: 'flame', icon: Flame, label: 'Hot' },
  { id: 'cloud', icon: Cloud, label: 'Cloud' },
  { id: 'sun', icon: Sun, label: 'Sun' },
  { id: 'moon', icon: Moon, label: 'Moon' },
  { id: 'sparkles', icon: Sparkles, label: 'Sparkle' },
  { id: 'feather', icon: Feather, label: 'Write' },
  { id: 'compass', icon: Compass, label: 'Compass' },
  { id: 'map', icon: Map, label: 'Map' },
  { id: 'mappin', icon: MapPin, label: 'Place' },
  { id: 'coffee', icon: Coffee, label: 'Coffee' },
  { id: 'pizza', icon: Pizza, label: 'Food' },
  { id: 'utensils', icon: Utensils, label: 'Dining' },
  { id: 'gift', icon: Gift, label: 'Gift' },
  { id: 'shoppingbag', icon: ShoppingBag, label: 'Shop' },
  { id: 'shoppingcart', icon: ShoppingCart, label: 'Cart' },
  { id: 'creditcard', icon: CreditCard, label: 'Card' },
  { id: 'wallet', icon: Wallet, label: 'Wallet' },
  { id: 'dollar', icon: DollarSign, label: 'Money' },
  { id: 'trending', icon: TrendingUp, label: 'Growth' },
  { id: 'barchart', icon: BarChart, label: 'Chart' },
  { id: 'piechart', icon: PieChart, label: 'Stats' },
  { id: 'activity', icon: Activity, label: 'Pulse' },
  { id: 'calendar', icon: Calendar, label: 'Calendar' },
  { id: 'clock', icon: Clock, label: 'Time' },
  { id: 'bell', icon: Bell, label: 'Alert' },
  { id: 'mail', icon: Mail, label: 'Mail' },
  { id: 'message', icon: MessageCircle, label: 'Chat' },
  { id: 'phone', icon: Phone, label: 'Phone' },
  { id: 'video', icon: Video, label: 'Video' },
  { id: 'mic', icon: Mic, label: 'Voice' },
  { id: 'headphones', icon: Headphones, label: 'Audio' },
  { id: 'film', icon: Film, label: 'Film' },
  { id: 'image', icon: Image, label: 'Photo' },
  { id: 'bookmark', icon: Bookmark, label: 'Save' },
  { id: 'tag', icon: Tag, label: 'Tag' },
  { id: 'flag', icon: Flag, label: 'Flag' },
  { id: 'award', icon: Award, label: 'Award' },
  { id: 'medal', icon: Medal, label: 'Medal' },
  { id: 'crown', icon: Crown, label: 'Crown' },
  { id: 'gem', icon: Gem, label: 'Gem' },
  { id: 'anchor', icon: Anchor, label: 'Anchor' },
  { id: 'plane', icon: Plane, label: 'Flight' },
  { id: 'car', icon: Car, label: 'Car' },
  { id: 'bike', icon: Bike, label: 'Bike' },
  { id: 'ship', icon: Ship, label: 'Ship' },
  { id: 'train', icon: Train, label: 'Train' },
  { id: 'bus', icon: Bus, label: 'Bus' },
  { id: 'tree', icon: Trees, label: 'Tree' },
  { id: 'leaf', icon: Leaf, label: 'Leaf' },
  { id: 'flower', icon: Flower, label: 'Flower' },
  { id: 'sprout', icon: Sprout, label: 'Grow' },
  { id: 'fish', icon: Fish, label: 'Fish' },
  { id: 'bird', icon: Bird, label: 'Bird' },
  { id: 'cat', icon: Cat, label: 'Cat' },
  { id: 'dog', icon: Dog, label: 'Dog' },
  { id: 'code', icon: Code, label: 'Code' },
  { id: 'terminal', icon: Terminal, label: 'Terminal' },
  { id: 'cpu', icon: Cpu, label: 'CPU' },
  { id: 'database', icon: Database, label: 'Data' },
  { id: 'server', icon: Server, label: 'Server' },
  { id: 'cloudicon', icon: Cloud, label: 'Cloud' },
  { id: 'wifi', icon: Wifi, label: 'Wifi' },
  { id: 'lock', icon: Lock, label: 'Lock' },
  { id: 'key', icon: Key, label: 'Key' },
  { id: 'shield', icon: Shield, label: 'Shield' },
  { id: 'eye', icon: Eye, label: 'View' },
  { id: 'search', icon: Search, label: 'Search' },
  { id: 'filter', icon: Filter, label: 'Filter' },
  { id: 'layers', icon: Layers, label: 'Layers' },
  { id: 'grid', icon: Grid, label: 'Grid' },
  { id: 'list', icon: List, label: 'List' },
  { id: 'pentool', icon: PenTool, label: 'Design' },
  { id: 'brush', icon: Brush, label: 'Paint' },
  { id: 'scissors', icon: Scissors, label: 'Cut' },
  { id: 'ruler', icon: Ruler, label: 'Measure' },
  { id: 'wrench', icon: Wrench, label: 'Tools' },
  { id: 'hammer', icon: Hammer, label: 'Build' },
  { id: 'puzzle', icon: Puzzle, label: 'Puzzle' },
  { id: 'gamepad', icon: Gamepad, label: 'Games' },
  { id: 'dumbbell', icon: Dumbbell, label: 'Fitness' },
  { id: 'mountain', icon: Mountain, label: 'Peak' },
  { id: 'umbrella', icon: Umbrella, label: 'Weather' },
  { id: 'tent', icon: Tent, label: 'Camp' },
  { id: 'backpack', icon: Backpack, label: 'Pack' },
  { id: 'watch', icon: Watch, label: 'Watch' },
  { id: 'glasses', icon: Glasses, label: 'Read' },
];

export const workspaceIconMap: Record<string, React.ElementType> = Object.fromEntries(
  WORKSPACE_ICONS.map((i) => [i.id, i.icon])
);

export const DEFAULT_WORKSPACE_ICON: React.ElementType = Hash;

export function getWorkspaceIcon(id?: string | null): React.ElementType {
  if (!id) return DEFAULT_WORKSPACE_ICON;
  return workspaceIconMap[id] || DEFAULT_WORKSPACE_ICON;
}
